make promise
Gavrilik/library-book pull request #4
Opened 2022-02-09 10:05 UTC by Gavrilik

2022-02-09 11:57 UTC, dmialeshka commented on src/features/user/user.controller.ts
>    @UseGuards(AuthGuard('local'))
change Local to JWT guar

2022-02-09 13:57 UTC, Gavrilik commented on src/features/user/user.controller.ts
>    @UseGuards(AuthGuard('local'))
change

2022-02-15 13:38 UTC, dmialeshka requested changes

2022-02-15 13:38 UTC, dmialeshka commented on package.json
> +    "@nestjs/sequelize": "^8.0.0",
do we need it?

2022-02-15 13:38 UTC, dmialeshka commented on package.json
> +    "sequelize": "^6.16.1",
the same question

2022-02-15 13:38 UTC, dmialeshka commented on src/app.module.ts
> +      entities: ['src/entity/**/*.ts'],
are you sure that is correct ?

2022-02-15 13:38 UTC, dmialeshka commented on src/app.module.ts
> +      entities: ['src/entity/**/*.ts'],
use class import instead of path

2022-02-15 13:38 UTC, dmialeshka commented on src/app.module.ts
> +  constructor(private connection: Connection) {}
do we need it ?

2022-02-15 13:38 UTC, dmialeshka commented on src/features/book/book.controller.ts
> +  create(@Body() createBookDto: CreateBookDto): Promise<any> {
fix type returns

2022-02-15 13:38 UTC, dmialeshka commented on src/features/book/book.controller.ts
> +  findAll(): Promise<any> {
fix type returns

2022-02-15 13:38 UTC, dmialeshka commented on src/features/book/book.controller.ts
> +    @Param('id') id: number,
fix id type

2022-02-15 13:38 UTC, dmialeshka commented on src/features/book/book.service.ts
> +import { User } from '../user/entities/user.entity';
do we need it here ?

2022-02-15 13:38 UTC, dmialeshka commented on src/features/book/book.service.ts
> +  async remove(id: number): Promise<void> {
why you use async await here ?

2022-02-15 13:38 UTC, dmialeshka commented on src/features/user/user.controller.ts
> +  findOne(@Param('id') id: number): Promise<any> {
fix returns type

2022-02-22 11:28 UTC, dmialeshka approved these changes

2022-02-22 14:00 UTC, merged